ASPNET/Лабораторная 2/Controllers/Lab2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAspNet2.Controllers
{
    public class Lab2Controller : Controller
    {
        // GET: Lab2
        public ActionResult ListOfPeople()
        {
            List<Person> people = new List<Person>();
            using (var db = new abcEntities())
            {
                people = db.People.OrderByDescending(x => x.Age)
                    .ThenBy(x => x.LastName)
                    .ThenBy(x => x.FirstName).ToList();
            }
            return View(people);
        }
        public ActionResult PersonDetails(Guid personId)
        {
            Person model = new Person();
            using (var db = new abcEntities())
            {
                model = db.People.Find(personId);
            }
            return View(model);
        }
    }
}

ASPNET/Лабораторная 2/Views/Lab2/ListOfPeople.cshtml
@model List<LW1.Models.Entities.Person>
@{
    ViewBag.Title = "ListOfPeople";
}

<h2>Лист участников опроса</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center">Наименование</th>
            <th class="text-center">Возраст</th>
            <th class="text-center">#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
            {
                <td>@person.LastName @person.FirstName @person.Patronymi</td>
                <td>@person.Age</td>
                <td>@Html.ActionLink("подробнее","PersonDetails","Lab2",new { personId = person.Id }, null )</td>
            }
    </tbody>
</table>